<Project>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Version>0.1.0-preview.2</Version>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/jenolaszlo-sketch/lattice-db-sharp</RepositoryUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <LatticeDbNativeVersion>0.15.0</LatticeDbNativeVersion>
    <LatticeDbNativeCommit>9800159e22e200f2b6888c7c6be1810adb695506</LatticeDbNativeCommit>
  </PropertyGroup>
</Project>
